name: Validate Commit Messages

on:
  push:
  pull_request:

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history to get all commits
    
    - name: Validate commit messages
      run: |
        # Determine commit range based on event type
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          # For PRs, validate commits in the PR
          COMMIT_RANGE="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
        else
          # For pushes, validate only the commits in this push
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            # New branch, validate only the latest commit
            COMMIT_RANGE="HEAD~1..HEAD"
          else
            # Existing branch, validate commits in this push
            COMMIT_RANGE="${{ github.event.before }}..${{ github.event.after }}"
          fi
        fi
        
        # Run the validation script
        ./scripts/validate-commits.sh --range "$COMMIT_RANGE" --verbose
