name: Validate Commit Messages

on:
  push:
  pull_request:

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history to get all commits
    
    - name: Validate commit messages
      run: |
        # Simple approach: always validate just the latest commit for now
        echo "Validating latest commit only..."
        echo "Current HEAD: $(git rev-parse HEAD)"
        echo "Latest commit message:"
        git log -1 --pretty=format:"%B"
        echo ""
        echo "Running validation..."
        
        # Make script executable
        chmod +x ./scripts/validate-commits.sh
        
        # Run validation on just the latest commit
        ./scripts/validate-commits.sh --range "HEAD~1..HEAD" --verbose
